In [7]:
import pandas as pd

data = {
    "name": ["Jatin", "Aryan", "Rahul", "Neha"],
    "marks": [90, 80, 95, 70],
    "city": ["Delhi", "Mumbai", "Pune", "Delhi"]
}

df = pd.DataFrame(data)

df

    name  marks    city
0  Jatin     90   Delhi
1  Aryan     80  Mumbai
2  Rahul     95    Pune
3   Neha     70   Delhi

In [8]:
df[df["marks"] > 85]

    name  marks   city
0  Jatin     90  Delhi
2  Rahul     95   Pune

In [ ]:
df