In [2]:
import pandas as pd

data = {
    "Name": ["Jatin", "Rahul", "Aman", "Priya"],
    "Age": [22, 25, 21, 24],
    "Salary": [50000, 70000, 45000, 80000]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
print(df)

    Name  Age  Salary
0  Jatin   22   50000
1  Rahul   25   70000
2   Aman   21   45000
3  Priya   24   80000

In [5]:
df[df["Age"] > 22]

    Name  Age  Salary
1  Rahul   25   70000
3  Priya   24   80000

In [6]:
df[(df["Age"] < 24) | (df["Salary"] > 75000)]

    Name  Age  Salary
0  Jatin   22   50000
2   Aman   21   45000
3  Priya   24   80000