In [1]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Jatin", "Rahul", "Aman", "Priya"],
    "Age": [22, np.nan, 21, 24],
    "Salary": [50000, 70000, np.nan, 80000]
}

df = pd.DataFrame(data)

print(df)

    Name   Age   Salary
0  Jatin  22.0  50000.0
1  Rahul   NaN  70000.0
2   Aman  21.0      NaN
3  Priya  24.0  80000.0

In [2]:
df.isna()

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True
3  False  False   False

In [3]:
df.dropna()

    Name   Age   Salary
0  Jatin  22.0  50000.0
3  Priya  24.0  80000.0

In [6]:
df.fillna(100)

    Name    Age   Salary
0  Jatin   22.0  50000.0
1  Rahul  100.0  70000.0
2   Aman   21.0    100.0
3  Priya   24.0  80000.0